services:
  db:
    image: postgres:17
    container_name: nhs_volunteers_db
    env_file: .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django-web:
    build: .
    container_name: nhs_volunteers_web
    env_file: .env.prod
    depends_on:
      - db
    volumes:
      - ./static:/app/staticfiles
    # temp exposing port
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: nhs_volunteers_nginx
    depends_on:
      - django-web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
      - ./frontend/dist:/usr/share/nginx/html:ro

volumes:
  postgres_data: